import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import IntlProvider from "./spin-match/IntlProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script src="https://www.youtube.com/game_api/v1" />
      </head>
      <body className={inter.className}>
        <IntlProvider>{children}</IntlProvider>
      </body>
    </html>
  );
}
